apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: infinigram
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-balanced
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infinigram-pileval-gpt2
spec:
  storageClassName: "infinigram"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: infinigram-api
    name: infinigram-pileval-gpt2
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/ai2-reviz/zones/us-west1-b/disks/infinigram-pileval-test
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infinigram-api
  name: infinigram-pileval-gpt2
spec:
  storageClassName: "infinigram"
  volumeName: infinigram-pileval-gpt2
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
