apiVersion: v1
kind: PersistentVolume
metadata:
  name: infinigram-v4-tulu-v3-1-mix
spec:
  storageClassName: "infinigram"
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: infinigram-api
    name: infinigram-v4-tulu-v3-1-mix
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/ai2-reviz/zones/us-west1-b/disks/$DISK_NAME
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infinigram-api
  name: infinigram-v4-tulu-v3-1-mix
spec:
  storageClassName: "infinigram"
  volumeName: infinigram-v4-tulu-v3-1-mix
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi