apiVersion: v1
kind: PersistentVolume
metadata:
  name: infinigram-v4-tulu-3-70b-adapt-llama
spec:
  storageClassName: "infinigram"
  capacity:
    storage: 11Gi 
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: infinigram-api
    name: infinigram-v4-tulu-3-70b-adapt-llama
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/ai2-reviz/zones/us-west1-b/disks/infinigram-v4-tulu-3-70b-adapt-llama
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infinigram-api
  name: infinigram-v4-tulu-3-70b-adapt-llama
spec:
  storageClassName: "infinigram"
  volumeName: infinigram-v4-tulu-3-70b-adapt-llama
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 11Gi
