apiVersion: v1
kind: Pod
metadata:
  name: infini-gram-writer 
spec:
  containers:
  - name: infini-gram-writer
    image: nginx:1.27.0-alpine 
    volumeMounts:
      - mountPath: /mnt/infini-gram-array/
        name: infinigram-array
  
  volumes:
    - name: infinigram-array
      persistentVolumeClaim:
        claimName: infinigram-dolma-1-7-writer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infinigram-dolma-1-7-writer
spec:
  storageClassName: "infinigram"
  capacity:
    storage: 22Ti
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: infinigram-api
    name: infinigram-dolma-1-7-writer
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/ai2-reviz/zones/us-west1-b/disks/infini-gram-dolma-1-7
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infinigram-api
  name: infinigram-dolma-1-7-writer
spec:
  storageClassName: "infinigram"
  volumeName: infinigram-dolma-1-7-writer
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 22Ti
